///////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gormgen, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST             //
///////////////////////////////////////////////////////////

package dq_user

import (
	"fmt"
	"time"

	"github.com/zhangdi168/dq-bot/internal/repository/mysql"

	"github.com/pkg/errors"
	"gorm.io/gorm"
)

func NewModel() *DqUser {
	return new(DqUser)
}

func NewQueryBuilder() *dqUserQueryBuilder {
	return new(dqUserQueryBuilder)
}

func (t *DqUser) Create(db *gorm.DB) (id int32, err error) {
	if err = db.Create(t).Error; err != nil {
		return 0, errors.Wrap(err, "create err")
	}
	return t.Id, nil
}

type dqUserQueryBuilder struct {
	order []string
	where []struct {
		prefix string
		value  interface{}
	}
	limit  int
	offset int
}

func (qb *dqUserQueryBuilder) buildQuery(db *gorm.DB) *gorm.DB {
	ret := db
	for _, where := range qb.where {
		ret = ret.Where(where.prefix, where.value)
	}
	for _, order := range qb.order {
		ret = ret.Order(order)
	}
	ret = ret.Limit(qb.limit).Offset(qb.offset)
	return ret
}

func (qb *dqUserQueryBuilder) Updates(db *gorm.DB, m map[string]interface{}) (err error) {
	db = db.Model(&DqUser{})

	for _, where := range qb.where {
		db.Where(where.prefix, where.value)
	}

	if err = db.Updates(m).Error; err != nil {
		return errors.Wrap(err, "updates err")
	}
	return nil
}

func (qb *dqUserQueryBuilder) Delete(db *gorm.DB) (err error) {
	for _, where := range qb.where {
		db = db.Where(where.prefix, where.value)
	}

	if err = db.Delete(&DqUser{}).Error; err != nil {
		return errors.Wrap(err, "delete err")
	}
	return nil
}

func (qb *dqUserQueryBuilder) Count(db *gorm.DB) (int64, error) {
	var c int64
	res := qb.buildQuery(db).Model(&DqUser{}).Count(&c)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		c = 0
	}
	return c, res.Error
}

func (qb *dqUserQueryBuilder) First(db *gorm.DB) (*DqUser, error) {
	ret := &DqUser{}
	res := qb.buildQuery(db).First(ret)
	if res.Error != nil && res.Error == gorm.ErrRecordNotFound {
		ret = nil
	}
	return ret, res.Error
}

func (qb *dqUserQueryBuilder) QueryOne(db *gorm.DB) (*DqUser, error) {
	qb.limit = 1
	ret, err := qb.QueryAll(db)
	if len(ret) > 0 {
		return ret[0], err
	}
	return nil, err
}

func (qb *dqUserQueryBuilder) QueryAll(db *gorm.DB) ([]*DqUser, error) {
	var ret []*DqUser
	err := qb.buildQuery(db).Find(&ret).Error
	return ret, err
}

func (qb *dqUserQueryBuilder) Limit(limit int) *dqUserQueryBuilder {
	qb.limit = limit
	return qb
}

func (qb *dqUserQueryBuilder) Offset(offset int) *dqUserQueryBuilder {
	qb.offset = offset
	return qb
}

func (qb *dqUserQueryBuilder) WhereId(p mysql.Predicate, value int32) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", p),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereIdIn(value []int32) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereIdNotIn(value []int32) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) OrderById(asc bool) *dqUserQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "id "+order)
	return qb
}

func (qb *dqUserQueryBuilder) WhereNickname(p mysql.Predicate, value string) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "nickname", p),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereNicknameIn(value []string) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "nickname", "IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereNicknameNotIn(value []string) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "nickname", "NOT IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) OrderByNickname(asc bool) *dqUserQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "nickname "+order)
	return qb
}

func (qb *dqUserQueryBuilder) WhereQqId(p mysql.Predicate, value string) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "qq_id", p),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereQqIdIn(value []int32) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "qq_id", "IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereQqIdNotIn(value []int32) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "qq_id", "NOT IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) OrderByQqId(asc bool) *dqUserQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "qq_id "+order)
	return qb
}

func (qb *dqUserQueryBuilder) WhereCreateAt(p mysql.Predicate, value time.Time) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_at", p),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereCreateAtIn(value []time.Time) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_at", "IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereCreateAtNotIn(value []time.Time) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "create_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) OrderByCreateAt(asc bool) *dqUserQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "create_at "+order)
	return qb
}

func (qb *dqUserQueryBuilder) WhereUpdateAt(p mysql.Predicate, value time.Time) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "update_at", p),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereUpdateAtIn(value []time.Time) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "update_at", "IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) WhereUpdateAtNotIn(value []time.Time) *dqUserQueryBuilder {
	qb.where = append(qb.where, struct {
		prefix string
		value  interface{}
	}{
		fmt.Sprintf("%v %v ?", "update_at", "NOT IN"),
		value,
	})
	return qb
}

func (qb *dqUserQueryBuilder) OrderByUpdateAt(asc bool) *dqUserQueryBuilder {
	order := "DESC"
	if asc {
		order = "ASC"
	}

	qb.order = append(qb.order, "update_at "+order)
	return qb
}
