
[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[language]
  local = "zh-cn"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "119.29.64.194:3306"
    name = "dqbot168"
    pass = "dqbot168"
    user = "dqbot168"

  [mysql.write]
    addr = "119.29.64.194:3306"
    name = "dqbot168"
    pass = "dqbot168"
    user = "dqbot168"

[redis]
  addr = "119.29.64.194:6789"
  db = "1"
  maxretries = 3
  minidleconns = 5
  pass = "dqbotredis"
  poolsize = 10

[bot]
  appid= 102005901
  token= "GhzKo5iMaVrkyUujR36pcju3DsvjGV7x"